version: '3'
services:
  # PostgreSQL Database Service
  postgres:
    image: postgres
    container_name: backend-postgres
    ports:
      - "5432:5432" # Expose PostgreSQL port
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Express App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "4000:4000" # Expose your app's port
    networks:
      - app-network
    depends_on:
      - postgres # Ensure the app starts after PostgreSQL
    environment:
      DB_URL: ${DB_URL}
      NODE_ENV: dev

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
