version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "6000:6000" # Map container's port 6000 to host's port 6000
    depends_on:
      - postgres
    environment:
      DB_URL: ${DB_URL}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TEST_DB_URL: ${TEST_DB_URL}
      NODE_ENV: ${NODE_ENV}
    command:
      [
        "sh",
        "-c",
        "sleep 10 &&  npm run migrate && npm start"
      ]

volumes:
  postgres-data:
